name = "testbot"
pages_build_output_dir = "./dist"
compatibility_date = "2024-06-14"
# compatibility_flags = ["nodejs_compat"]

[vars]
BOT_INFO = """{
    "id": 7245643709,
    "is_bot": true,
    "first_name": "testbot",
    "username": "test5173bot",
    "can_join_groups": true,
    "can_read_all_group_messages": false,
    "supports_inline_queries": false,
    "can_connect_to_business": false
}"""